# Example workspace schema
# Defines entity types and their structure

entities:
  tasks:
    directory: tasks
    naming: "{slug}.md"
    frontmatter:
      required: [title, status]
      optional: [priority, due, tags]
      defaults:
        status: open

  notes:
    directory: notes
    naming: "{slug}.md"
    frontmatter:
      required: [title]
      optional: [tags, created]

  projects:
    directory: projects
    naming: "{code}.md"
    frontmatter:
      required: [code, name, status]
      optional: [description, tags]
      defaults:
        status: active
